---
title: "ART"
author: "Mike"
date: "2020/6/30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reference

1. [系统学习机器学习之神经网络（五）--ART](https://blog.csdn.net/App_12062011/article/details/53463372)

1. [Adaptive resonance theory art neural network | soft computing (in Hindi)](https://www.youtube.com/watch?v=P6_j2smSrdI)


---

# Package

```{r message=FALSE, warning=FALSE}
library(dplyr) # data manipulation
library(RSNNS)  # ART
# source('Source_ART.R') # ModelPerformance
```

---

# Data

```{r}
data("snnsData")
class(snnsData)
str(snnsData)

class(snnsData$art1_letters.pat)

DT::datatable(snnsData$art1_letters.pat) #26個字母
```

---

# Modeling

## Setting

```{r}
data <- as.data.frame(snnsData$art1_letters.pat)
new_data <- read.csv('NewData.csv', encoding = 'utf-8')

dimX=7
dimY=5 
f2Units = 26 # 共分幾群

```

## Plot
```{r}
inputMaps <- matrixToActMapList(data, nrow=dimX, ncol=dimY) # 將資料轉為矩陣

par(mfrow=c(3,6))
for (i in 1:18) {
  tryCatch(plotActMap(inputMaps[[i]]),error = function(e){NULL})
}
```

## Model
```{r}
model.ART1 <- art1(data, dimX=dimX, dimY=dimY, f2Units = f2Units) 
model.ART1 # Parameters
```

## Group
```{r}
# 分群結果
group.ART1 <- encodeClassLabels(model.ART1$fitted.values)
names(group.ART1) = rownames(data)
group.ART1

```

## Predict
```{r}
newInputMaps <- matrixToActMapList(new_data, nrow=dimX, ncol=dimY) # 將資料轉為矩陣

par(mfrow=c(3,6))
for (i in 1:18) {
  tryCatch(plotActMap(newInputMaps[[i]]),error = function(e){NULL})
}

```

